### ISSUE TITLE
Initialization crash

### ISSUE THREAD

**Issue by josemifever** [processout/processout-android#77]
Hi mates! we are experiences a HUGE amount of crashes within our latest release, using your 3DS sdk. Let me paste the trace:

```
Caused by java.lang.ClassNotFoundException: Didn't find class "com.checkout.threeds.sec.PackageUpdateBroadcastReceiver" on path: DexPathList[[zip file "/data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/base.apk", zip file "/data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/split_config.arm64_v8a.apk", zip file "/data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/split_config.en.apk", zip file "/data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/lib/arm64, /data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/base.apk!/lib/arm64-v8a, /data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~Z2_Rcn-n6_ygT4MpjMUr8g==/com.feverup.fever-OP_kL6N4LYa0pY36sgULGw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
       at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4282)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7884)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Versions: 
'com.processout:processout-android:4.2.0'
'com.processout:processout-android-checkout-3ds:4.2.0'
Transitive dep: 
![image](https://github.com/processout/processout-android/assets/98746994/f11d02ed-a668-4cae-a266-db723f71b510)

This happens the first time the app is opened after the update, after that the crash does not appear. 
Seems that this class doesn't exist, but is referenced in the manifest :S

**Comment by vitalii-vanziak-cko** [comment]
Hey @josemifever,
We just released SDK update **4.3.0**, which includes fix for this issue.
