### ISSUE TITLE
ClassCastException when enabling R8 fullMode

### ISSUE THREAD

**Issue by puboe** [processout/processout-android#79]
Hey!

We are trying to enable [R8 fullMode](https://developer.android.com/build/shrink-code#full-mode) in our app and we're getting a weird `ClassCastException` (see stacktrace below) when initializing the ProcessOut SDK via the `ProcessOut.configure(...)` method.

I was able to reproduce this issue in ProcessOut's test app (see [this branch with the details](https://github.com/puboe/processout-android/tree/r8-fullmode))

The steps to reproduce are the following:

1. Enable minifying and shrinkResources
```
minifyEnabled true
shrinkResources true
```
2. Add the following line to `gradle.properties`:
```
android.enableR8.fullMode=true
``` 
3. Run the app, it will crash while starting.

**Stacktrace**

```kotlin
FATAL EXCEPTION: main
    Process: com.processout.example.staging.debug, PID: 8366
    java.lang.RuntimeException: Unable to create application com.processout.example.ProcessOutExampleApplication: java.lang.ClassCastException
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    Caused by: java.lang.ClassCastException
        at androidx.appcompat.app.ToolbarActionBar$$ExternalSyntheticThrowCCEIfNotNull0.m(R8$$SyntheticClass:0)
        at com.processout.sdk.di.NetworkGraphImpl.<init>(NetworkGraph.kt:58)
        at com.processout.sdk.api.ProcessOut$Companion.configure(ProcessOut.kt:72)
        at com.processout.example.ProcessOutExampleApplication.onCreate(ProcessOutExampleApplication.kt:11)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by vitalii-vanziak-cko** [comment]
Hey! @puboe 
According to R8 FAQ there is issues with Retrofit ProGuard rules that doesn't work with R8 full mode as-is.
https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#retrofit

I've tried various suggestions from their issues tracker and here's what worked:
```
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation interface com.processout.sdk.api.network.** { *; }
```

So keeping `retrofit2.Response` and additionally all our Retrofit interfaces.
Please try and let us know if it works with your setup, we will add this rules in our next release.
